export enum IpcKeys {
    STORE_SET = "STORE_SET",
    STORE_GET = "STORE_GET",

    GET_SONGS = "GET_SONGS",
    PLAY_SONG = "PLAY_SONG",
    SONG_STREAM = "SONG_STREAM",
    SONG_INFO = "SONG_INFO",
    SONG_DELETE = "SONG_DELETE",

    RPC_SONG = "RPC_SONG",

    APP_GET_VERSION = "APP_GET_VERSION",
    MINIMIZE_WINDOW = "MINIMIZE_WINDOW",
    MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW",
    EXIT = "EXIT"
}