export enum IpcKeys {
    STORE_SET = "STORE_SET",
    STORE_GET = "STORE_GET",

    GET_SONGS = "GET_SONGS",
    PLAY_SONG = "PLAY_SONG",
    SONG_STREAM = "SONG_STREAM",
    SONG_INFO = "SONG_INFO",
    SONG_DELETE = "SONG_DELETE",

    RPC_SONG = "RPC_SONG"
}