export enum IpcKeys {
    STORE_SET = "STORE_SET",
    STORE_GET = "STORE_GET",

    GET_SONGS = "GET_SONGS",
    PLAY_SONG = "PLAY_SONG",
    SONG_STREAM = "SONG_STREAM",
    SONG_ADD = "SONG_ADD",
    SONG_DELETE = "SONG_DELETE"
}